"""Convert SVG icons to C header with embedded RGBA pixel data."""
import sys, os
from PyQt6.QtWidgets import QApplication
from PyQt6.QtGui import QImage, QPainter
from PyQt6.QtCore import Qt
from PyQt6.QtSvg import QSvgRenderer

app = QApplication(sys.argv)
res_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'resources')

icons = [
    ('gear',         'gear.svg',         24),
    ('thermometer',  'thermometer.svg',  24),
    ('fan',          'fan.svg',          24),
    ('wave',         'wave.svg',         24),
    ('ram',          'ram.svg',          24),
    ('gauge',        'gauge.svg',        24),
    ('graphic_card', 'graphic-card.svg', 48),
]

header = '#pragma once\n// Auto-generated by gen_icons.py\n\n'
for name, filename, sz in icons:
    path = os.path.join(res_dir, filename)
    renderer = QSvgRenderer(path)
    img = QImage(sz, sz, QImage.Format.Format_ARGB32)
    img.fill(0)
    p = QPainter(img)
    renderer.render(p)
    p.end()

    data = []
    for y in range(sz):
        for x in range(sz):
            c = img.pixelColor(x, y)
            data.extend([c.red(), c.green(), c.blue(), c.alpha()])

    header += f'static const int ICON_{name.upper()}_SIZE = {sz};\n'
    header += f'static const unsigned char ICON_{name.upper()}[] = {{\n'
    for i in range(0, len(data), 16):
        header += '    ' + ','.join(str(b) for b in data[i:i+16]) + ',\n'
    header += '};\n\n'
    print(f'  {name}: {sz}x{sz}')

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'icons_data.h'), 'w') as f:
    f.write(header)
print('Done.')
